raw_csv = """message_msgType,message.msgTypeBase,dataiku_category
accessible-objects-count,accessible,DROP_DELETE
accessible-objects-list,accessible,DROP_DELETE
action-add-to-scenario,action,DROP_DELETE
action-build,action,DROP_DELETE
action-change-connection,action,DROP_DELETE
action-change-python-env,action,DROP_DELETE
action-change-recipes-engines,action,DROP_DELETE
action-change-spark-config,action,DROP_DELETE
action-change-spark-engine,action,DROP_DELETE
action-change-spark-pipelineability,action,DROP_DELETE
action-change-sql-pipelineability,action,DROP_DELETE
action-clear,action,DROP_DELETE
action-copy-all,action,DROP_DELETE
action-delete,action,DROP_DELETE
action-set-auto-count-of-records2,action,DROP_DELETE
action-set-virtualizable,action,DROP_DELETE
action-share,action,DROP_DELETE
action-sync-metastore,action,DROP_DELETE
action-tag,action,DROP_DELETE
action-triggered-survey-decline,action,DROP_DELETE
action-unshare,action,DROP_DELETE
action-update-status,action,DROP_DELETE
add-checklist,add,DROP_DELETE
add-git-tag,add,DROP_DELETE
add-model-api-endpoint,add,DROP_DELETE
add-objects-to-workspace,add,DROP_DELETE
admin-build-container-base-images,admin,ADMINISTRATION
admin-code-env-browse-resources,admin,ADMINISTRATION
admin-code-env-create,admin,ADMINISTRATION
admin-code-env-delete,admin,ADMINISTRATION
admin-code-env-export,admin,ADMINISTRATION
admin-code-env-get-resources-env-vars,admin,DROP_DELETE
admin-code-env-get,admin,DROP_DELETE
admin-code-env-package-presets-python,admin,ADMINISTRATION
admin-code-env-save,admin,ADMINISTRATION
admin-code-env-update,admin,ADMINISTRATION
admin-code-env-usages,admin,ADMINISTRATION
admin-code-envs-create,admin,ADMINISTRATION
admin-code-envs-get-log,admin,DROP_DELETE
admin-code-envs-get,admin,DROP_DELETE
admin-code-envs-list-logs,admin,READING_LISTING
admin-code-envs-list,admin,READING_LISTING
admin-code-envs-update,admin,ADMINISTRATION
admin-code-envs-usages,admin,ADMINISTRATION
admin-connection-delete,admin,ADMINISTRATION
admin-connection-get,admin,DROP_DELETE
admin-connection-save,admin,ADMINISTRATION
admin-connections-list,admin,READING_LISTING
admin-diagnostics-downsload,admin,ADMINISTRATION
admin-diagnostics-run,admin,ADMINISTRATION
admin-folder-edit-create,admin,ADMINISTRATION
admin-folder-edit-delete,admin,ADMINISTRATION
admin-folder-edit-get,admin,DROP_DELETE
admin-folder-edit-list,admin,READING_LISTING
admin-folder-edit-preview-image,admin,ADMINISTRATION
admin-folder-edit-save,admin,ADMINISTRATION
admin-folder-edit-upload,admin,ADMINISTRATION
admin-get-audit-buffer,admin,DROP_DELETE
admin-get-authorization-matrix,admin,DROP_DELETE
admin-get-instance-info,admin,DROP_DELETE
admin-get-license-status,admin,DROP_DELETE
admin-get-projects-integrations,admin,DROP_DELETE
admin-get-scheduled-tasks-status,admin,DROP_DELETE
admin-get-usage-summary,admin,DROP_DELETE
admin-global-tags-info,admin,ADMINISTRATION
admin-integrations-save,admin,ADMINISTRATION
admin-licensing-status-get,admin,DROP_DELETE
admin-log-get,admin,DROP_DELETE
admin-logs-list,admin,READING_LISTING
admin-model-cache-get-details,admin,DROP_DELETE
admin-personal-apikeys-list,admin,READING_LISTING
admin-plugin-install-from-store,admin,ADMINISTRATION
admin-plugin-save-settings,admin,ADMINISTRATION
admin-plugin-upload,admin,ADMINISTRATION
admin-plugins-get,admin,DROP_DELETE
admin-plugins-list,admin,READING_LISTING
admin-push-container-base-images,admin,ADMINISTRATION
admin-read-apikeys,admin,READING_LISTING
admin-read-settings,admin,READING_LISTING
admin-sanity-check-get-codes,admin,DROP_DELETE
admin-sanity-check-get-exclusions,admin,DROP_DELETE
admin-sanity-check-get-latest-run,admin,DROP_DELETE
admin-sanity-check-get-running-job,admin,DROP_DELETE
admin-sanity-check-run,admin,ADMINISTRATION
admin-save-settings,admin,ADMINISTRATION
admin-test-container-exec-conf,admin,ADMINISTRATION
admin-user-trial-start-success,admin,ADMINISTRATION
admin-user-trial-start,admin,ADMINISTRATION
admin-variables-read,admin,READING_LISTING
admin-variables-save,admin,ADMINISTRATION
admin-webapps-list-all-states,admin,READING_LISTING
agent-logs-list,agent,READING_LISTING
agent-test,agent,GENAI_LLM
agent-tool-create,agent,GENAI_LLM
agent-tool-get-descriptor,agent,DROP_DELETE
agent-tool-get-metadata,agent,DROP_DELETE
agent-tool-get,agent,DROP_DELETE
agent-tool-run,agent,GENAI_LLM
agent-tool-save,agent,GENAI_LLM
agent-tool-test,agent,GENAI_LLM
agent-tools-list,agent,READING_LISTING
ai-generate-recipe-create,ai,GENAI_LLM
ai-generate-recipe-edit,ai,GENAI_LLM
ai-generate-recipe-generate,ai,GENAI_LLM
alert-banner-dismissed,alert,DROP_DELETE
allow-browser-notification,allow,DROP_DELETE
analyse-category-clearselected,analyse,STATISTIC_ANALYTICS
analyse-category-longtailgroup,analyse,STATISTIC_ANALYTICS
analyse-category-merge,analyse,STATISTIC_ANALYTICS
analyse-category-removeone,analyse,STATISTIC_ANALYTICS
analyse-category-removeselected,analyse,STATISTIC_ANALYTICS
analyse-full-sample-configuration-open,analyse,STATISTIC_ANALYTICS
analyse-numerical-clipoutliers,analyse,STATISTIC_ANALYTICS
analyse-numerical-rmoutliers,analyse,STATISTIC_ANALYTICS
analyse-open,analyse,STATISTIC_ANALYTICS
analysis-charts-open,analysis,STATISTIC_ANALYTICS
analysis-cml-deploy-cluster-recipe-to-the-flow,analysis,STATISTIC_ANALYTICS
analysis-cml-deploy-model-to-the-flow,analysis,STATISTIC_ANALYTICS
analysis-cml-redeploy-model-to-the-flow,analysis,STATISTIC_ANALYTICS
analysis-cmltask-model-charts-open,analysis,STATISTIC_ANALYTICS
analysis-cmltask-model-table-open,analysis,STATISTIC_ANALYTICS
analysis-create-experiment-for-lab-models,analysis,STATISTIC_ANALYTICS
analysis-get-mltasks,analysis,DROP_DELETE
analysis-get-post-script-schema,analysis,DROP_DELETE
analysis-get,analysis,DROP_DELETE
analysis-import-lab-models-to-experiment,analysis,STATISTIC_ANALYTICS
analysis-list,analysis,READING_LISTING
analysis-ml-get-log,analysis,DROP_DELETE
analysis-ml-get-settings,analysis,DROP_DELETE
analysis-ml-revert-script-to-session,analysis,STATISTIC_ANALYTICS
analysis-mltask-list-queued-sessions,analysis,READING_LISTING
analysis-pml-charts-open,analysis,STATISTIC_ANALYTICS
analysis-pml-deploy-model-to-the-flow,analysis,STATISTIC_ANALYTICS
analysis-pml-redeploy-model-to-the-flow,analysis,STATISTIC_ANALYTICS
analysis-prediction-task-deploy,analysis,STATISTIC_ANALYTICS
analysis-prediction-task-get-settings,analysis,DROP_DELETE
analysis-prediction-task-set-settings,analysis,STATISTIC_ANALYTICS
analysis-prediction-task-train,analysis,STATISTIC_ANALYTICS
analysis-script-open,analysis,STATISTIC_ANALYTICS
anum-facet-add,anum,DROP_DELETE
api-deployer-deploy-version-in-existing-deployment,api,APIS
api-deployer-deploy-version-in-new-deployment,api,APIS
api-deployer-deployment-copy,api,APIS
api-deployer-deployment-create,api,APIS
api-deployer-deployment-delete,api,APIS
api-deployer-deployment-deploy,api,APIS
api-deployer-deployment-endpoint-selection-change,api,APIS
api-deployer-deployment-save,api,APIS
api-deployer-deployment-update,api,APIS
api-deployer-infra-setup,api,APIS
api-deployer-packages-delete,api,APIS
api-deployer-publish-to-deployer,api,APIS
api-deployer-service-create,api,APIS
api-designer-openapi-toggle,api,APIS
api-designer-test-queries,api,APIS
apideployer-deployment-audit-storage-url,apideployer,OTHER
apideployer-deployment-create,apideployer,OTHER
apideployer-deployment-get-last-action,apideployer,DROP_DELETE
apideployer-deployment-get-open-api,apideployer,DROP_DELETE
apideployer-deployment-get,apideployer,DROP_DELETE
apideployer-deployment-governance-status-get,apideployer,DROP_DELETE
apideployer-deployment-peek-action-progress,apideployer,OTHER
apideployer-deployment-sync,apideployer,OTHER
apideployer-deployment-test,apideployer,OTHER
apideployer-deployments-list-heavy-status,apideployer,READING_LISTING
apideployer-deployments-list-tags,apideployer,READING_LISTING
apideployer-deployments-list,apideployer,READING_LISTING
apideployer-get-status,apideployer,DROP_DELETE
apideployer-infra-audit-storage-url,apideployer,OTHER
apideployer-infra-create,apideployer,APIS
apideployer-infra-create,apideployer,OTHER
apideployer-infra-get-light-status,apideployer,DROP_DELETE
apideployer-infra-get-settings,apideployer,DROP_DELETE
apideployer-infra-get-vertexai-accelerator-types,apideployer,DROP_DELETE
apideployer-infra-get-vertexai-instance-types,apideployer,DROP_DELETE
apideployer-infra-get,apideployer,DROP_DELETE
apideployer-infra-save,apideployer,APIS
apideployer-infra-save,apideployer,OTHER
apideployer-infra-status,apideployer,OTHER
apideployer-infras-list,apideployer,READING_LISTING
apideployer-services-get,apideployer,DROP_DELETE
apideployer-services-list,apideployer,READING_LISTING
app-create-instance,app,APPLICATION_DESIGNER
app-create-or-update-plugin,app,APPLICATION_DESIGNER
app-get-access-info,app,DROP_DELETE
app-instances-fitering,app,APPLICATION_DESIGNER
app-instantiate,app,APPLICATION_DESIGNER
app-list-fitering,app,READING_LISTING
app-recreated,app,APPLICATION_DESIGNER
app-switch-app-type,app,APPLICATION_DESIGNER
app-test-instance,app,APPLICATION_DESIGNER
app-tile-dashboard-link,app,APPLICATION_DESIGNER
app-tile-dataset-settings-edit,app,APPLICATION_DESIGNER
app-tile-dataset-settings-edit,app,DATASET
app-tile-download-dashboard,app,APPLICATION_DESIGNER
app-tile-download-dataset,app,APPLICATION_DESIGNER
app-tile-download-dataset,app,DATASET
app-tile-download-folder,app,APPLICATION_DESIGNER
app-tile-folder-files-edit,app,APPLICATION_DESIGNER
app-tile-folder-link,app,APPLICATION_DESIGNER
app-tile-fs-dataset-browse,app,APPLICATION_DESIGNER
app-tile-fs-dataset-browse,app,DATASET
app-tile-fs-dataset-edit,app,APPLICATION_DESIGNER
app-tile-fs-dataset-edit,app,DATASET
app-tile-fs-dataset-modal,app,APPLICATION_DESIGNER
app-tile-fs-dataset-modal,app,DATASET
app-tile-fs-dataset-test,app,APPLICATION_DESIGNER
app-tile-fs-dataset-test,app,DATASET
app-tile-inline-dataset,app,APPLICATION_DESIGNER
app-tile-inline-dataset,app,DATASET
app-tile-project-variables-modal,app,APPLICATION_DESIGNER
app-tile-project-variables-save,app,APPLICATION_DESIGNER
app-tile-scenario-current-run,app,APPLICATION_DESIGNER
app-tile-scenario-last-run,app,APPLICATION_DESIGNER
app-tile-scenario-run,app,APPLICATION_DESIGNER
app-tile-sql-dataset-modal,app,APPLICATION_DESIGNER
app-tile-sql-dataset-modal,app,CODING
app-tile-upload-dataset-delete,app,APPLICATION_DESIGNER
app-tile-upload-dataset-delete,app,DATASET
app-tile-upload-dataset-drop,app,APPLICATION_DESIGNER
app-tile-upload-dataset-drop,app,DATASET
app-tile-upload-dataset-edit,app,APPLICATION_DESIGNER
app-tile-upload-dataset-edit,app,DATASET
app-tile-upload-folder-delete,app,APPLICATION_DESIGNER
app-tile-upload-folder-drop,app,APPLICATION_DESIGNER
application-open,application,APPLICATION_DESIGNER
apps-get-instance,apps,DROP_DELETE
apps-get,apps,DROP_DELETE
apps-instantiate,apps,APPLICATION_DESIGNER
apps-list,apps,READING_LISTING
apps-test-update,apps,APPLICATION_DESIGNER
article-add-attachment,article,WIKI_ARTICAL_DISCUSSIONS
article-change-parent,article,WIKI_ARTICAL_DISCUSSIONS
article-create,article,WIKI_ARTICAL_DISCUSSIONS
article-delete,article,WIKI_ARTICAL_DISCUSSIONS
article-drop-files,article,WIKI_ARTICAL_DISCUSSIONS
article-get,article,DROP_DELETE
article-insert-image,article,WIKI_ARTICAL_DISCUSSIONS
article-insert-link,article,WIKI_ARTICAL_DISCUSSIONS
article-remove-attachment,article,WIKI_ARTICAL_DISCUSSIONS
article-rename,article,WIKI_ARTICAL_DISCUSSIONS
article-save-layout,article,WIKI_ARTICAL_DISCUSSIONS
article-save,article,WIKI_ARTICAL_DISCUSSIONS
article-set,article,WIKI_ARTICAL_DISCUSSIONS
automation-bundle-set-settings,automation,AUTOMATION
catalog-get-data-source-dataset-details,catalog,DROP_DELETE
catalog-list-dashboards,catalog,READING_LISTING
catalog-search-done,catalog,READING_LISTING
catalog-search,catalog,READING_LISTING
chart-colorgroup-base-on-another-column-dropped,chart,CHARTS_DASHBOARD
chart-create,chart,CHARTS_DASHBOARD
chart-delete-color-rule-group,chart,CHARTS_DASHBOARD
chart-delete-color-rule,chart,CHARTS_DASHBOARD
chart-delete,chart,CHARTS_DASHBOARD
chart-download,chart,CHARTS_DASHBOARD
chart-duplicate,chart,CHARTS_DASHBOARD
chart-new-color-rule-group,chart,CHARTS_DASHBOARD
chart-new-color-rule,chart,CHARTS_DASHBOARD
chart-new-gauge-range,chart,CHARTS_DASHBOARD
chart-new-reference-line,chart,CHARTS_DASHBOARD
chart-paste-action,chart,CHARTS_DASHBOARD
chart-paste,chart,CHARTS_DASHBOARD
chart-publish,chart,CHARTS_DASHBOARD
chart-reference-line-delete,chart,CHARTS_DASHBOARD
chart-reference-line-source-change,chart,CHARTS_DASHBOARD
chart-sample-setting-update,chart,CHARTS_DASHBOARD
chart-type-change,chart,CHARTS_DASHBOARD
check-deleted-objects,check,DROP_DELETE
check-downstream-buildable,check,DROP_DELETE
check-failed,check,DROP_DELETE
checks-add-check,checks,STATISTIC_ANALYTICS
checks-add-dataset-in-flow,checks,STATISTIC_ANALYTICS
checks-compute-now,checks,STATISTIC_ANALYTICS
checks-preview-check,checks,STATISTIC_ANALYTICS
checks-save,checks,STATISTIC_ANALYTICS
checks-selector-save,checks,STATISTIC_ANALYTICS
clicked-item,clicked,DROP_DELETE
clientEvent.msgType,base_msgType,dataiku_category
clustering-facts-edit-node,clustering,MLOPS
clustering-hierarchy-edit-node,clustering,MLOPS
clustering-hierarchy-page-open,clustering,MLOPS
clustering-hierarchy-sort-features,clustering,MLOPS
clustering-train,clustering,MLOPS
clusters-action-create,clusters,CONTAINERS
clusters-action-delete,clusters,CONTAINERS
clusters-action-markstopped,clusters,CONTAINERS
clusters-action-save,clusters,CONTAINERS
clusters-action-start,clusters,CONTAINERS
clusters-create,clusters,CONTAINERS
clusters-get-status,clusters,DROP_DELETE
clusters-get,clusters,DROP_DELETE
clusters-k8s-count-nodes-pods,clusters,CONTAINERS
clusters-k8s-has-metrics-server,clusters,CONTAINERS
clusters-k8s-kubectl-command,clusters,CONTAINERS
clusters-k8s-monitoring-deployments,clusters,CONTAINERS
clusters-k8s-monitoring-describe-object,clusters,CONTAINERS
clusters-k8s-monitoring-jobs,clusters,CONTAINERS
clusters-k8s-monitoring-namespaces,clusters,CONTAINERS
clusters-k8s-monitoring-nodes,clusters,CONTAINERS
clusters-k8s-monitoring-pods,clusters,CONTAINERS
clusters-k8s-monitoring-services,clusters,CONTAINERS
clusters-k8s-retrieve-nodes-metrics,clusters,CONTAINERS
clusters-list-logs,clusters,READING_LISTING
clusters-list,clusters,READING_LISTING
clusters-monitoring-deployments-viewed,clusters,CONTAINERS
clusters-monitoring-jobs-viewed,clusters,CONTAINERS
clusters-monitoring-nodes-viewed,clusters,CONTAINERS
clusters-monitoring-pods-viewed,clusters,CONTAINERS
clusters-monitoring-services-viewed,clusters,CONTAINERS
clusters-start,clusters,CONTAINERS
clusters-status-created,clusters,CONTAINERS
clusters-status-deleted,clusters,CONTAINERS
clusters-status-markstopped,clusters,CONTAINERS
clusters-status-saved,clusters,CONTAINERS
clusters-status-started,clusters,CONTAINERS
clusters-stop,clusters,CONTAINERS
coachmark-global-disable,coachmark,DROP_DELETE
coachmark-series-disabled,coachmark,DROP_DELETE
coachmark-series-start,coachmark,DROP_DELETE
code_studio_action_changes,code_studio_action_changes,CODING
code_studio_action_conflicts_cancel,code_studio_action_conflicts_cancel,CODING
code_studio_action_conflicts_erase,code_studio_action_conflicts_erase,CODING
code_studio_action_conflicts_forget,code_studio_action_conflicts_forget,CODING
code_studio_action_conflicts,code_studio_action_conflicts,CODING
code_studio_action_create,code_studio_action_create,CODING
code_studio_action_customcommand,code_studio_action_customcommand,CODING
code_studio_action_new,code_studio_action_new,CODING
code_studio_action_publish,code_studio_action_publish,CODING
code_studio_action_refresh,code_studio_action_refresh,CODING
code_studio_action_reset,code_studio_action_reset,CODING
code_studio_action_start,code_studio_action_start,CODING
code_studio_action_stop,code_studio_action_stop,CODING
code_studio_action_sync,code_studio_action_sync,CODING
code_studio_action_syncstop,code_studio_action_syncstop,CODING
code_studio_copy,code_studio_copy,CODING
code_studio_files_viewed,code_studio_files_viewed,CODING
code_studio_logs_viewed,code_studio_logs_viewed,CODING
code_studio_view_viewed,code_studio_view_viewed,CODING
code-studio-backend,code,CODING
code-studio-blocks-list-types,code,READING_LISTING
code-studio-current-users,code,CODING
code-studio-files,code,CODING
code-studio-folder-edit-get,code,DROP_DELETE
code-studio-folder-edit-list,code,READING_LISTING
code-studio-folder-edit-save,code,CODING
code-studio-object-create,code,CODING
code-studio-object-files,code,CODING
code-studio-object-get,code,DROP_DELETE
code-studio-object-open-file,code,CODING
code-studio-object-restart,code,CODING
code-studio-object-state,code,CODING
code-studio-object-stop,code,CODING
code-studio-object-try-restart-server,code,CODING
code-studio-objects-list-types,code,READING_LISTING
code-studio-objects-list,code,READING_LISTING
code-studio-protected-view,code,CODING
code-studio-standalone-view,code,CODING
code-studio-stop,code,CODING
code-studio-template-build,code,CODING
code-studio-template-create,code,CODING
code-studio-template-delete,code,CODING
code-studio-template-export,code,CODING
code-studio-template-get,code,DROP_DELETE
code-studio-template-logs,code,CODING
code-studio-template-resources-list,code,READING_LISTING
code-studio-template-save,code,CODING
code-studio-template-usage,code,CODING
code-studio-templates-get,code,DROP_DELETE
code-studio-templates-list-heads,code,READING_LISTING
code-studio-templates-list-types,code,READING_LISTING
code-studio-templates-list,code,READING_LISTING
code-studio-templates-save,code,CODING
code-studio-webapp-edit,code,WEBAPPS
code-studio-webapp-edit,webapp,WEBAPPS
code-studios-list-heads,code,READING_LISTING
codestudiotemplate_action_addblock,codestudiotemplate_action_addblock,CODING
codestudiotemplate_action_build,codestudiotemplate_action_build,CODING
codestudiotemplate_action_create,codestudiotemplate_action_create,CODING
codestudiotemplate_action_delete,codestudiotemplate_action_delete,CODING
codestudiotemplate_action_export,codestudiotemplate_action_export,CODING
codestudiotemplate_action_new,codestudiotemplate_action_new,CODING
codestudiotemplate_action_removeblock,codestudiotemplate_action_removeblock,CODING
codestudiotemplate_action_save,codestudiotemplate_action_save,CODING
codestudiotemplate_action_usages,codestudiotemplate_action_usages,CODING
codestudiotemplate_definition_viewed,codestudiotemplate_definition_viewed,CODING
codestudiotemplate_history_viewed,codestudiotemplate_history_viewed,CODING
codestudiotemplate_info_viewed,codestudiotemplate_info_viewed,CODING
codestudiotemplate_logs_viewed,codestudiotemplate_logs_viewed,CODING
codestudiotemplate_permissions_viewed,codestudiotemplate_permissions_viewed,CODING
codestudiotemplate_resources_viewed,codestudiotemplate_resources_viewed,CODING
codestudiotemplate_usage_viewed,codestudiotemplate_usage_viewed,CODING
columns-selector-save,columns,DROP_DELETE
compare-column-values-close,compare,MLOPS
compare-column-values-open,compare,MLOPS
compute-drift,compute,MLOPS
compute-resource-usage-complete,compute,MLOPS
compute-resource-usage-start,compute,MLOPS
compute-resource-usage-update,compute,MLOPS
conditional-formatting-migrate,conditional,STATISTIC_ANALYTICS
conditional-formatting-pane-open,conditional,STATISTIC_ANALYTICS
conditional-formatting-rule-add,conditional,STATISTIC_ANALYTICS
connect-points-status,connect,CHARTS_DASHBOARD
connection-create,connection,READING_LISTING
connection-get-credentials,connection,DROP_DELETE
connection-get-details,connection,DROP_DELETE
connection-get-info,connection,DROP_DELETE
connection-get,connection,DROP_DELETE
connection-info-denied,connection,READING_LISTING
connection-list-mass-import-schemas,connection,READING_LISTING
connection-list-mass-import-sources,connection,READING_LISTING
connection-list-mass-import-sql-tables,connection,READING_LISTING
connection-list-sql-schemas,connection,READING_LISTING
connection-mass-import-candidates,connection,READING_LISTING
connection-sql-list-fields,connection,READING_LISTING
connection-sql-list-tables,connection,READING_LISTING
connection-test-customllm,connection,READING_LISTING
connection-test-ec2,connection,READING_LISTING
connection-test-vertexai,connection,READING_LISTING
connections-list-names,connections,READING_LISTING
connections-list,connections,READING_LISTING
container-conf-test,container,CONTAINERS
containers-get-execution,containers,DROP_DELETE
containers-get-file,containers,DROP_DELETE
containers-get,containers,DROP_DELETE
containers-list,containers,READING_LISTING
containers-put-file,containers,CONTAINERS
convert-to-prompt-recipe,prompt,GENAI_LLM
copy-subflow,copy,FLOW
create-and-publish-to-api-deployer,create,APIS
create-and-publish-to-api-deployer,create,DROP_DELETE
create-api-endpoint,create,APIS
create-api-endpoint,create,DROP_DELETE
create-api-service,create,APIS
create-api-service,create,DROP_DELETE
create-dataset,create,DATASET
create-dataset,create,DROP_DELETE
create-recipe,create,DROP_DELETE
creating-recipes-get,creating,DROP_DELETE
custom-fields-save,custom,STATISTIC_ANALYTICS
custom-measure-cancel,custom,STATISTIC_ANALYTICS
custom-measure-edited,custom,STATISTIC_ANALYTICS
custom-measure-saved,custom,STATISTIC_ANALYTICS
custom-webapp-edit,custom,STATISTIC_ANALYTICS
dashboard-create,dashboard,CHARTS_DASHBOARD
dashboard-cross-filtering-enabled-change,dashboard,CHARTS_DASHBOARD
dashboard-export-download,dashboard,CHARTS_DASHBOARD
dashboard-export-form-displayed,dashboard,CHARTS_DASHBOARD
dashboard-exported-from-dashboard-universe,dashboard,CHARTS_DASHBOARD
dashboard-filters-add-filter,dashboard,CHARTS_DASHBOARD
dashboard-filters-change-dataset,dashboard,CHARTS_DASHBOARD
dashboard-filters-change-dataset,dashboard,DATASET
dashboard-filters-create-cancel,dashboard,CHARTS_DASHBOARD
dashboard-filters-create-open,dashboard,CHARTS_DASHBOARD
dashboard-filters-create-success,dashboard,CHARTS_DASHBOARD
dashboard-filters-first-use-in-session,dashboard,CHARTS_DASHBOARD
dashboard-filters-sample-setting-update,dashboard,CHARTS_DASHBOARD
dashboard-filters-save,dashboard,CHARTS_DASHBOARD
dashboard-filters-url-copy,dashboard,CHARTS_DASHBOARD
dashboard-insight-create,dashboard,CHARTS_DASHBOARD
dashboard-new-insight,dashboard,CHARTS_DASHBOARD
dashboard-page-create,dashboard,CHARTS_DASHBOARD
dashboard-read-meta,dashboard,READING_LISTING
dashboard-save,dashboard,CHARTS_DASHBOARD
dashboard-to-edit-mode-switch,dashboard,CHARTS_DASHBOARD
dashboard-to-view-mode-switch,dashboard,CHARTS_DASHBOARD
dashboard-use-denied,dashboard,CHARTS_DASHBOARD
dashboards-create-cross-filter,dashboards,CHARTS_DASHBOARD
dashboards-download-export,dashboards,CHARTS_DASHBOARD
dashboards-export,dashboards,CHARTS_DASHBOARD
dashboards-list,dashboards,READING_LISTING
dashboards-read-meta,dashboards,READING_LISTING
data-catalog-search-from-home,data,STATISTIC_ANALYTICS
data-collection-add-object-cancel,data,STATISTIC_ANALYTICS
data-collection-add-object-open,data,STATISTIC_ANALYTICS
data-collection-creation,data,STATISTIC_ANALYTICS
data-collection-deletion,data,STATISTIC_ANALYTICS
data-collection-get-info,data,DROP_DELETE
data-collection-get-item-details,data,DROP_DELETE
data-collection-list-tags,data,READING_LISTING
data-collection-list-with-details,data,READING_LISTING
data-collection-object-added,data,STATISTIC_ANALYTICS
data-collection-recent-datasets,data,STATISTIC_ANALYTICS
data-lineage-access,data,STATISTIC_ANALYTICS
data-lineage-open-manual-lineage-modal,data,STATISTIC_ANALYTICS
data-quality-compute-rules-on-single-partition,data,STATISTIC_ANALYTICS
data-quality-edit-config,data,STATISTIC_ANALYTICS
data-quality-get-config,data,DROP_DELETE
data-quality-get-dataset-status-last-each-partition,data,DROP_DELETE
data-quality-get-dataset-status-timeline,data,DROP_DELETE
data-quality-get-dataset-summary-status-for-day,data,DROP_DELETE
data-quality-get-dataset-summary-status,data,DROP_DELETE
data-quality-get-monitoring,data,DROP_DELETE
data-quality-get-project-current-status,data,DROP_DELETE
data-quality-has-dataset-rule-history,data,STATISTIC_ANALYTICS
data-quality-set-monitoring,data,STATISTIC_ANALYTICS
data-quality-template-create,data,STATISTIC_ANALYTICS
data-quality-template-use,data,STATISTIC_ANALYTICS
data-quality-visit-monitoring-page,data,STATISTIC_ANALYTICS
dataiku-answers-ask-question,answers,GENAI_LLM
dataiku-answers-ask-question,dataiku,GENAI_LLM
dataiku-answers-clear-history,answers,GENAI_LLM
dataiku-answers-clear-history,dataiku,GENAI_LLM
dataiku-answers-delete-all-conversations,answers,GENAI_LLM
dataiku-answers-delete-all-conversations,dataiku,GENAI_LLM
dataiku-answers-delete-conversation,answers,GENAI_LLM
dataiku-answers-delete-conversation,dataiku,GENAI_LLM
dataiku-answers-error,answers,GENAI_LLM
dataiku-answers-error,dataiku,GENAI_LLM
dataiku-answers-give-feedback,answers,GENAI_LLM
dataiku-answers-give-feedback,dataiku,GENAI_LLM
dataiku-answers-new-conversation,answers,GENAI_LLM
dataiku-answers-new-conversation,dataiku,GENAI_LLM
dataiku-answers-open,answers,GENAI_LLM
dataiku-answers-open,dataiku,GENAI_LLM
dataset-change-display-mode,dataset,DATASET
dataset-charts-open,dataset,DATASET
dataset-charts-read-metadata,dataset,READING_LISTING
dataset-charts-read,dataset,READING_LISTING
dataset-clear-data,dataset,DATASET
dataset-clear-samples,dataset,DATASET
dataset-compute-data-quality-rules,dataset,DATASET
dataset-compute-status,dataset,DATASET
dataset-create,dataset,DATASET
dataset-data-quality-rule-create,dataset,DATASET
dataset-delete,dataset,DATASET
dataset-detect-partitioning,dataset,DATASET
dataset-detect-settings,dataset,DATASET
dataset-detectformat-done,dataset,DATASET
dataset-detectformat-onetype-done,dataset,DATASET
dataset-detectformat-onetype-start,dataset,DATASET
dataset-detectformat-start,dataset,DATASET
dataset-discard-schema-changed,dataset,DATASET
dataset-edit-status,dataset,DATASET
dataset-editable-read,dataset,READING_LISTING
dataset-editable-save,dataset,DATASET
dataset-explore-get-options,dataset,DROP_DELETE
dataset-explore-read-meta,dataset,READING_LISTING
dataset-explore-save-meta,dataset,DATASET
dataset-export,dataset,DATASET
dataset-get-full-info,dataset,DROP_DELETE
dataset-get,dataset,DROP_DELETE
dataset-new-managed-box,dataset,DATASET
dataset-preview-done,dataset,DATASET
dataset-preview-start,dataset,DATASET
dataset-read-data-sample,dataset,READING_LISTING
dataset-read-data,dataset,READING_LISTING
dataset-read-meta,dataset,READING_LISTING
dataset-read-schema,dataset,READING_LISTING
dataset-read-status,dataset,READING_LISTING
dataset-rename-open-modal,dataset,DATASET
dataset-rename,dataset,DATASET
dataset-sample-settings-update,dataset,DATASET
dataset-save-schema,dataset,DATASET
dataset-save,dataset,DATASET
dataset-schema-reload,dataset,DATASET
dataset-table-ddl,dataset,DATASET
dataset-test,dataset,DATASET
dataset-upload-add-file-uploadbox,dataset,DATASET
dataset-upload-add-file,dataset,DATASET
dataset-upload-create-uploadbox,dataset,DATASET
dataset-upload-list-files,dataset,READING_LISTING
dataset-upload-remove-file-uploadbox,dataset,DATASET
dataset-upload-remove-file,dataset,DATASET
dataset-verify-read,dataset,READING_LISTING
datasets-list,datasets,READING_LISTING
datastory-integration-check,datastory,GENAI_LLM
delete-dataset-data-quality-rule,delete,DATASET
delete-dataset-data-quality-rule,delete,OTHER
denied,denied,DROP_DELETE
deployer-hooks-create,deployer,DEPLOYER
deployer-hooks-edit-cancel,deployer,DEPLOYER
deployer-hooks-open,deployer,DEPLOYER
deployment-monitoring-creation-failure,deployment,DEPLOYER
deployment-monitoring-tab-visited,deployment,DEPLOYER
design-bundle-create,design,AUTOMATION
design-bundle-delete,design,AUTOMATION
design-bundle-get,design,DROP_DELETE
design-bundle-governance-status-get,design,DROP_DELETE
design-bundles-list,design,READING_LISTING
discussion-close,discussion,WIKI_ARTICAL_DISCUSSIONS
discussion-counts,discussion,WIKI_ARTICAL_DISCUSSIONS
discussion-delete,discussion,WIKI_ARTICAL_DISCUSSIONS
discussion-edit-reply,discussion,WIKI_ARTICAL_DISCUSSIONS
discussion-edit-topic,discussion,WIKI_ARTICAL_DISCUSSIONS
discussion-reply,discussion,WIKI_ARTICAL_DISCUSSIONS
discussions-ack,discussions,WIKI_ARTICAL_DISCUSSIONS
discussions-get,discussions,DROP_DELETE
docextract-screenshot,docextract,GENAI_LLM
doctor-compute-explanations,doctor,MLOPS
doctor-compute-pdp,doctor,MLOPS
doctor-compute-shapley-feature-importance,doctor,MLOPS
download-flow-documentation,download,MISC_RECIPES
download-model-documentation,download,MISC_RECIPES
dss-internal-code-env-check-codeenv-use-for-pii,dss,ADMINISTRATION
dss-internal-code-env-check-codeenv-use-for-rag,dss,ADMINISTRATION
dss-internal-code-env-check,dss,ADMINISTRATION
dss-internal-code-env-get-supported-interpreters,dss,DROP_DELETE
dss-license-update,dss,ADMINISTRATION
dss-version-commit,dss,ADMINISTRATION
dss-visualizations-list,dss,READING_LISTING
dynamic-measure-source-change,dynamic,GENAI_LLM
evaluation-store-create,evaluation,MLOPS
experiment-tracking-runs-charts-toggle-metrics-or-params,experiment,MLOPS
experiment-tracking-scroll-to-run-id,experiment,MLOPS
experiment-tracking-sort-experiments-table,experiment,MLOPS
experiment-tracking-sort-runs-table,experiment,MLOPS
experiment-tracking-toggle-runs-column,experiment,MLOPS
experiments-get,experiments,DROP_DELETE
experiments-list,experiments,READING_LISTING
explain-code-request-successful,explain,GENAI_LLM
explain-flow-zone-request-successful,explain,GENAI_LLM
explain-project-request-successful,explain,GENAI_LLM
explanation-request-aborted,explanation,GENAI_LLM
export-create,export,MISC_RECIPES
export-download,export,MISC_RECIPES
export-ready,export,READING_LISTING
exports-list,exports,READING_LISTING
externalinfras-get-vertexai-project,externalinfras,DROP_DELETE
externalinfras-list-vertexai-endpoints,externalinfras,READING_LISTING
externalinfras-list-vertexai-projects,externalinfras,READING_LISTING
flow-build-computable-find-outputs-next,flow,FLOW
flow-build-computable-find-outputs-preview-failed,flow,FLOW
flow-build-computable-find-outputs-preview,flow,FLOW
flow-build-computable-find-outputs-start,flow,FLOW
flow-build-computable-preview,flow,FLOW
flow-build-computable-start-failed,flow,FLOW
flow-build-computable-start,flow,FLOW
flow-context-menu-build-downstream-from-recipe,flow,FLOW
flow-context-menu-build,flow,FLOW
flow-context-menu-dataset-reload-schema,flow,DATASET
flow-context-menu-dataset-reload-schema,flow,FLOW
flow-context-menu-delete-multi,flow,FLOW
flow-context-menu-delete,flow,FLOW
flow-context-menu-fold,flow,FLOW
flow-context-menu-insertrecipe,flow,FLOW
flow-context-menu-mark-as-built,flow,FLOW
flow-context-menu-open,flow,FLOW
flow-context-menu-propagate-schema,flow,FLOW
flow-context-menu-select-predecessors-multi,flow,FLOW
flow-context-menu-select-predecessors,flow,FLOW
flow-context-menu-select-successors-multi,flow,FLOW
flow-context-menu-select-successors,flow,FLOW
flow-context-menu-snipandreconnect,flow,FLOW
flow-document-generator-custom,flow,FLOW
flow-document-generator-default,flow,FLOW
flow-documentation-export,flow,FLOW
flow-download-export,flow,FLOW
flow-export-download,flow,FLOW
flow-export-form-displayed,flow,FLOW
flow-export,flow,FLOW
flow-exported,flow,FLOW
flow-filter-apply,flow,FLOW
flow-graph-set-selection-strategy,flow,FLOW
flow-job-done,flow,FLOW
flow-job-start,flow,FLOW
flow-object-build-failed,flow,FLOW
flow-object-build-start,flow,FLOW
flow-object-build-success,flow,FLOW
flow-object-use-as-source,flow,FLOW
flow-omnibox-error,flow,FLOW
flow-omnibox-keyword-add,flow,FLOW
flow-omnibox-suggestion-open,flow,FLOW
flow-omnibox-suggestion-select,flow,FLOW
flow-omnibox-tool-start,flow,FLOW
flow-preview-update,flow,FLOW
flow-read,flow,READING_LISTING
flow-run-recipe-find-outputs-next,flow,FLOW
flow-run-recipe-find-outputs-start-failed,flow,FLOW
flow-run-recipe-find-outputs-start,flow,FLOW
flow-run-recipe-start-failed,flow,FLOW
flow-run-recipe-start,flow,FLOW
flow-selector-all-checkbox-change,flow,FLOW
flow-selector-display-change,flow,FLOW
flow-selector-zoom-toggle-change,flow,FLOW
flow-tool-start,flow,FLOW
flow-view-select-focused,flow,FLOW
flow-view-value-select,flow,FLOW
flow-zone-create,flow,FLOW
flow-zone-delete,flow,FLOW
flow-zone-edit,flow,FLOW
flow-zone-get,flow,DROP_DELETE
flow-zone-graph-get,flow,DROP_DELETE
flow-zone-item-add,flow,FLOW
flow-zone-items-move-to,flow,FLOW
flow-zone-items-share-to,flow,FLOW
flow-zone-items-unshare-from,flow,FLOW
flow-zone-retrieve-zone-item,flow,FLOW
flow-zone-update,flow,FLOW
flow-zones-list,flow,READING_LISTING
folder-create,folder,FOLDERS
folder-project-default-summary-get,folder,DROP_DELETE
folder-project-delete,folder,FOLDERS
folder-project-list-contents,folder,READING_LISTING
folder-project-list-readers,folder,READING_LISTING
folder-project-list-root-contents,folder,READING_LISTING
folder-project-list,folder,READING_LISTING
folder-project-move-items,folder,FOLDERS
folder-project-settings-get,folder,DROP_DELETE
folder-project-settings-update,folder,FOLDERS
folder-project-summary-get,folder,DROP_DELETE
folder-read-status,folder,READING_LISTING
folder-test-partitioning,folder,FOLDERS
fsprovider-browse,fsprovider,DROP_DELETE
fsprovider-fs-browse,fsprovider,DROP_DELETE
fsprovider-list,fsprovider,DROP_DELETE
fsprovider-test,fsprovider,DROP_DELETE
fsproviders-list,fsproviders,READING_LISTING
future-abort,future,DROP_DELETE
future-get,future,DROP_DELETE
futures-list,futures,READING_LISTING
fuzzy-join-params,fuzzy,VISUAL_RECIPES
gantt-to-job,gantt,SCENARIOS
generate-sql-query,generate,GENAI_LLM
geo-join-params,geo,VISUAL_RECIPES
geo-preview-popup-displayed,geo,VISUAL_RECIPES
get-auth-info-no-auth,get,DROP_DELETE
get-connection-types-pinned,get,DROP_DELETE
get-data-lineage,get,DROP_DELETE
get-dataset-current-daily-status,get,DROP_DELETE
get-default-assumed-timezone,get,DROP_DELETE
get-image-embeddings-pretrained-models,get,DROP_DELETE
get-insertable-fragments,get,DROP_DELETE
get-last-run-partitions,get,DROP_DELETE
get-metadata,get,DROP_DELETE
get-monitored-project-summary-statuses,get,DROP_DELETE
get-notebook,get,DROP_DELETE
get-project-folders-interests,get,DROP_DELETE
get-recipe-descriptors-failed,get,DROP_DELETE
get-sentence-embeddings-pretrained-models,get,DROP_DELETE
git-add-tag,git,GIT
git-merge-request_action_merge,git,GIT
git-merge-request_action_resolve-file,git,GIT
git-merge-request_cancel,git,GIT
git-merge-request_create,git,GIT
git-merge-request_update,git,GIT
git-remove-tag,git,GIT
global-finder-item-open,global,DROP_DELETE
global-finder-search,global,DROP_DELETE
govern-abandon-sign-off,govern,GOVERN
govern-cancel-abandon,govern,GOVERN
govern-delegate-review,govern,GOVERN
govern-edit-review,govern,GOVERN
govern-govern-action,govern,GOVERN
govern-navigate-artifactmenu,govern,GOVERN
govern-navigate-page,govern,GOVERN
govern-open,govern,GOVERN
govern-request-review,govern,GOVERN
govern-reset-sign-off,govern,GOVERN
govern-selecttab-rightpanel,govern,GOVERN
govern-sort-table,govern,GOVERN
govern-submit-review,govern,GOVERN
govern-subscribe-notifications,govern,GOVERN
govern-toggle-rightpanel,govern,GOVERN
help-open-get-help,help,DROP_DELETE
help-open-menu,help,DROP_DELETE
import-external-tables,import,MISC_RECIPES
in-memory-api-key-create,in,APIS
in-memory-api-key-create,in,OTHER
inbox-search,inbox,DROP_DELETE
init-write-session,init,DROP_DELETE
insert-snippet,insert,DROP_DELETE
insight-list,insight,READING_LISTING
insight-pin,insight,READING_LISTING
insight-read-meta,insight,READING_LISTING
insight-save,insight,READING_LISTING
instance-info-get,instance,DROP_DELETE
instance-sanity-check-run,instance,ADMINISTRATION
instances-delete,instances,ADMINISTRATION
integration-create,integration,DROP_DELETE
integration-delete,integration,DROP_DELETE
integration-list,integration,DROP_DELETE
interactive-scoring-compare-button,interactive,MLOPS
interactive-scoring-export-button,interactive,MLOPS
interactive-scoring,interactive,MLOPS
interests-get,interests,DROP_DELETE
interests-star,interests,DROP_DELETE
interests-users-list,interests,DROP_DELETE
interests-watch,interests,DROP_DELETE
internal-api-key-creation,internal,DROP_DELETE
internal-api-key-deletion,internal,DROP_DELETE
internal-debug,internal,DROP_DELETE
item-accessibility-update,item,DROP_DELETE
job-abort,job,SCENARIOS
job-delete,job,SCENARIOS
job-download-status,job,SCENARIOS
job-get-status,job,DROP_DELETE
job-preview,job,SCENARIOS
job-retry,job,SCENARIOS
job-start-spark-history-server,job,CODING
job-start,job,SCENARIOS
jobs-list,jobs,READING_LISTING
jupyter-create-kernel-context,jupyter,CODING
jupyter-delete-kernel-context,jupyter,CODING
jupyter-get-session-path,jupyter,DROP_DELETE
jupyter-get-user-authorization,jupyter,DROP_DELETE
jupyter-get-user-authorized-projects,jupyter,DROP_DELETE
jupyter-git-commit-checkpoint,jupyter,CODING
jupyter-git-commit-file,jupyter,CODING
jupyter-git-rename-checkpoint,jupyter,CODING
jupyter-git-rename-file,jupyter,CODING
jupyter-notebook-export-prepare,jupyter,CODING
jupyter-notebook-sessions,jupyter,CODING
jupyter-notebooks-get,jupyter,DROP_DELETE
jupyter-notebooks-list,jupyter,READING_LISTING
jupyter-notebooks-unload,jupyter,CODING
jupyter-notebooks-update,jupyter,CODING
knowledge-bank-contextual-menu-build,knowledge,GENAI_LLM
knowledge-bank-download,knowledge,GENAI_LLM
knowledge-bank-get-path,knowledge,DROP_DELETE
knowledge-bank-get-recipe-info,knowledge,DROP_DELETE
knowledge-bank-get-retrieval-augmented-llm-list,knowledge,DROP_DELETE
knowledge-bank-get,knowledge,DROP_DELETE
knowledge-bank-list-vector-store-connections,knowledge,READING_LISTING
knowledge-bank-list,knowledge,READING_LISTING
knowledge-bank-save,knowledge,GENAI_LLM
knowledge-bank-set-metadata-columns-schema,knowledge,GENAI_LLM
kubernetes-cluster-usage-status,kubernetes,CONTAINERS
labeling-reject-record,labeling,MLOPS
labeling-save-answer,labeling,MLOPS
labeling-save-review,labeling,MLOPS
labeling-validate-all,labeling,MLOPS
labelingtasks-list,labelingtasks,READING_LISTING
lambda-create,lambda,DROP_DELETE
lambda-deploy-to-dev,lambda,DROP_DELETE
lambda-get-package-summary,lambda,DROP_DELETE
lambda-get-packages,lambda,DROP_DELETE
lambda-get,lambda,DROP_DELETE
lambda-list,lambda,DROP_DELETE
lambda-play-test-queries,lambda,DROP_DELETE
learning-curves-compute,learning,MLOPS
lib-edit-action-denied,lib,DROP_DELETE
license-update,license,MLOPS
lineage-inspect,lineage,READING_LISTING
list-dataset-types-with-no-connection,list,READING_LISTING
list-git-remote-references,list,READING_LISTING
list-heavy-status,list,READING_LISTING
list-interested-users,list,READING_LISTING
list-popular-datasets,list,READING_LISTING
list-published-projects,list,READING_LISTING
llm-completion-query,llm,GENAI_LLM
llm-embedding-query,llm,GENAI_LLM
llm-embeddings,llm,GENAI_LLM
llm-mesh-knowledge-bank-load,llm,GENAI_LLM
llm-mesh-knowledge-banks-get,llm,DROP_DELETE
llm-mesh-knowledge-banks-list,llm,READING_LISTING
llm-mesh-llms-list,llm,READING_LISTING
load-flow-filter-settings,load,READING_LISTING
login-failure,login,DROP_DELETE
login-success,login,DROP_DELETE
logout,logout,DROP_DELETE
managed-folder-clear,managed,FOLDERS
managed-folder-download,managed,FOLDERS
managed-folder-get-path-details,managed,DROP_DELETE
managed-folder-get-path,managed,DROP_DELETE
managed-folder-read-meta,managed,READING_LISTING
managed-folder-upload,managed,FOLDERS
managedfolder-browse-path,managedfolder,FOLDERS
managedfolder-contextual-menu-build,managedfolder,FOLDERS
managedfolder-contextual-menu-clear,managedfolder,FOLDERS
managedfolder-create-folder,managedfolder,FOLDERS
managedfolder-create,managedfolder,FOLDERS
managedfolder-delete-item,managedfolder,FOLDERS
managedfolder-delete-items,managedfolder,FOLDERS
managedfolder-delete,managedfolder,FOLDERS
managedfolder-download,managedfolder,FOLDERS
managedfolder-get,managedfolder,DROP_DELETE
managedfolder-list-content,managedfolder,READING_LISTING
managedfolder-move-items,managedfolder,FOLDERS
managedfolder-preview-item,managedfolder,FOLDERS
managedfolder-rename-item,managedfolder,FOLDERS
managedfolder-save,managedfolder,FOLDERS
managedfolder-upload,managedfolder,FOLDERS
managedfolder-view-content,managedfolder,FOLDERS
managedfolders-list,managedfolders,READING_LISTING
me-compute-subpopulation,me,MLOPS
meanings-list,meanings,READING_LISTING
merge-request-list,merge,READING_LISTING
metrics-add-dataset-in-flow,metrics,STATISTIC_ANALYTICS
metrics-add-probe,metrics,STATISTIC_ANALYTICS
metrics-check-inserted,metrics,STATISTIC_ANALYTICS
metrics-clear,metrics,STATISTIC_ANALYTICS
metrics-compute-now,metrics,STATISTIC_ANALYTICS
metrics-edit-run-settings,metrics,STATISTIC_ANALYTICS
metrics-open-metric-modal,metrics,STATISTIC_ANALYTICS
metrics-preview-probe,metrics,STATISTIC_ANALYTICS
metrics-refresh-partition-list,metrics,READING_LISTING
metrics-save,metrics,STATISTIC_ANALYTICS
metrics-selector-save,metrics,STATISTIC_ANALYTICS
ml-exploration-computation-started,ml,MLOPS
ml-exploration-computation-succeeded,ml,MLOPS
ml-exploration-constraints-opened,ml,MLOPS
ml-interactive-model-compute,ml,MLOPS
ml-learning-curve-get-computed,ml,DROP_DELETE
ml-model-delete,ml,MLOPS
ml-model-export-predicted-data,ml,MLOPS
ml-model-save-meta,ml,MLOPS
ml-prediction-get-global-explanations,ml,DROP_DELETE
ml-prediction-get-preparation-script,ml,DROP_DELETE
ml-prediction-grant-fs-read-acls,ml,READING_LISTING
ml-prediction-model-get-collector-data,ml,DROP_DELETE
ml-prediction-model-get-column-importance,ml,DROP_DELETE
ml-prediction-model-get-details,ml,DROP_DELETE
ml-prediction-model-get-features-distribution,ml,DROP_DELETE
ml-prediction-model-get-schema,ml,DROP_DELETE
ml-prediction-model-get-split-desc,ml,DROP_DELETE
ml-prediction-pdp-computation,ml,MLOPS
mlflow-experiments-get-by-name,mlflow,DROP_DELETE
mlflow-experiments-search,mlflow,MLOPS
mlflow-log_batch,mlflow,MLOPS
mlflow-log_model,mlflow,MLOPS
mlflow-log_param,mlflow,MLOPS
mlflow-run-create,mlflow,MLOPS
mlflow-run-get,mlflow,DROP_DELETE
mlflow-run-update,mlflow,MLOPS
mlflow-runs-search,mlflow,MLOPS
mltask-abort,mltask,MLOPS
mltask-copy-algorithms,mltask,MLOPS
mltask-copy-features-handling,mltask,MLOPS
mltask-delete-queued-session,mltask,MLOPS
mltask-duplicate,mltask,MLOPS
mltask-train-queue,mltask,MLOPS
model-evaluation-comparison-appended,model,MLOPS
model-evaluation-comparison-created,model,MLOPS
model-evaluation-store-menu-opening,model,MLOPS
model-evaluation-store-refresh-status,model,MLOPS
model-export,model,MLOPS
model-read-status,model,READING_LISTING
modelcomparisons-browse-comparables,modelcomparisons,MLOPS
modelcomparisons-create,modelcomparisons,MLOPS
modelcomparisons-full-info-get,modelcomparisons,DROP_DELETE
modelcomparisons-get-models-details,modelcomparisons,DROP_DELETE
modelcomparisons-list,modelcomparisons,READING_LISTING
modelcomparisons-save,modelcomparisons,MLOPS
modelevaluationstore-compute-status,modelevaluationstore,MLOPS
modelevaluationstore-contextual-menu-build,modelevaluationstore,MLOPS
modelevaluationstore-create,modelevaluationstore,MLOPS
modelevaluationstore-get-evaluation-details,modelevaluationstore,DROP_DELETE
modelevaluationstore-get-full-info,modelevaluationstore,DROP_DELETE
modelevaluationstore-get,modelevaluationstore,DROP_DELETE
modelevaluationstore-list-evaluations,modelevaluationstore,READING_LISTING
modelevaluationstore-read-status,modelevaluationstore,READING_LISTING
modelevaluationstore-save,modelevaluationstore,MLOPS
modelevaluationstores-list-heads,modelevaluationstores,READING_LISTING
modelevaluationstores-list-with-accessible,modelevaluationstores,READING_LISTING
modelevaluationstores-list,modelevaluationstores,READING_LISTING
monitoring-activity-metrics,monitoring,DEPLOYER
new-managed-folder-modal-create,new,MLOPS
new-managed-folder-modal-open,new,MLOPS
new-model-evaluation-store-modal-create,evaluation,MLOPS
new-model-evaluation-store-modal-create,new,MLOPS
new-model-evaluation-store-modal-open,evaluation,MLOPS
new-model-evaluation-store-modal-open,new,MLOPS
not-admin,not,DROP_DELETE
notebook-create,notebook,CODING
notebook-ipython-create-recipe,notebook,CODING
notebook-ipython-save-back-to-recipe,notebook,CODING
notebook-jupyter-create,notebook,CODING
notebook-jupyter-upload,notebook,CODING
notebook-query-abort,notebook,CODING
notebook-read-history,notebook,READING_LISTING
notebook-read-meta,notebook,READING_LISTING
notebook-sql-create,notebook,CODING
notebooks-list,notebooks,READING_LISTING
notebooks-unload,notebooks,CODING
object-commit-prepare,object,DROP_DELETE
object-commit,object,DROP_DELETE
object-get-log,object,DROP_DELETE
object-read-status,object,DROP_DELETE
object-revert,object,DROP_DELETE
object-sharing-disable-sharing,object,DROP_DELETE
object-sharing-enable-sharing,object,DROP_DELETE
object-sharing-modal-cancel,object,DROP_DELETE
object-sharing-modal-open,object,DROP_DELETE
object-sharing-modal-save,object,DROP_DELETE
object-sharing-object-share,object,DROP_DELETE
object-sharing-object-unshare,object,DROP_DELETE
object-sharing-type-change,object,DROP_DELETE
opals-error,opals,DROP_DELETE
opals-help-click-item,opals,DROP_DELETE
opals-help-close,opals,DROP_DELETE
opals-help-dock,opals,DROP_DELETE
opals-help-load-error,opals,DROP_DELETE
opals-help-minimize,opals,DROP_DELETE
opals-help-open,opals,DROP_DELETE
opals-help-search,opals,DROP_DELETE
opals-home-banner-dismiss-card,opals,DROP_DELETE
opals-home-banner-display,opals,DROP_DELETE
opals-home-banner-hide,opals,DROP_DELETE
opals-home-banner-show,opals,DROP_DELETE
open-dss-landing-page,open,DROP_DELETE
page-dataset-loaded,page,DROP_DELETE
page-tour-closed,page,DROP_DELETE
page-tour-dismissed,page,DROP_DELETE
page-tour-started,page,DROP_DELETE
paste-modal-submit,paste,MLOPS
patternbuilder,patternbuilder,PREPARE
php-sort-by-star,php,DROP_DELETE
plugin-clone,plugin,PLUGINS
plugin-convert-to-customcode,plugin,PLUGINS
plugin-create-code-env,plugin,PLUGINS
plugin-delete,plugin,PLUGINS
plugin-dev-action-denied,plugin,PLUGINS
plugin-dev-add-custom+fields-json,plugin,PLUGINS
plugin-dev-add-dataset-python,plugin,PLUGINS
plugin-dev-add-fs+provider-python,plugin,PLUGINS
plugin-dev-add-macro-python,plugin,PLUGINS
plugin-dev-add-parameter+set-generic,plugin,PLUGINS
plugin-dev-add-preparation+processor-jython,plugin,PLUGINS
plugin-dev-create-code-env-python,plugin,PLUGINS
plugin-dev-create,plugin,PLUGINS
plugin-download,plugin,PLUGINS
plugin-get-commit-diff,plugin,DROP_DELETE
plugin-get-presets,plugin,DROP_DELETE
plugin-get-settings,plugin,DROP_DELETE
plugin-install-from-zip,plugin,PLUGINS
plugin-python-do,plugin,PLUGINS
plugin-set-settings,plugin,PLUGINS
plugin-settings-changed,plugin,PLUGINS
plugin-upload,plugin,PLUGINS
plugindev-add-custom-llm,plugindev,PLUGINS
plugindev-add-python-code-env,plugindev,PLUGINS
plugindev-add-python-runnable,plugindev,PLUGINS
plugindev-check-upload-content,plugindev,PLUGINS
plugindev-create-content,plugindev,PLUGINS
plugindev-create,plugindev,PLUGINS
plugindev-delete-content,plugindev,PLUGINS
plugindev-delete,plugindev,PLUGINS
plugindev-download,plugindev,PLUGINS
plugindev-edit,plugindev,PLUGINS
plugindev-get-coontent,plugindev,DROP_DELETE
plugindev-get,plugindev,DROP_DELETE
plugindev-git-delete-branches,plugindev,PLUGINS
plugindev-git-fetch,plugindev,PLUGINS
plugindev-git-pull,plugindev,PLUGINS
plugindev-git-push,plugindev,PLUGINS
plugindev-git-set-remote,plugindev,PLUGINS
plugindev-git-switch-branch,plugindev,PLUGINS
plugindev-list-contents,plugindev,READING_LISTING
plugindev-move-content,plugindev,PLUGINS
plugindev-reload,plugindev,PLUGINS
plugindev-rename-content,plugindev,PLUGINS
plugindev-set-content-muliple,plugindev,PLUGINS
plugindev-set-content,plugindev,PLUGINS
plugindev-upload-content,plugindev,PLUGINS
plugindev-use-venv,plugindev,PLUGINS
plugindev-validate,plugindev,PLUGINS
plugins-git-full-status,plugins,PLUGINS
plugins-git-list-branches,plugins,READING_LISTING
plugins-git-log,plugins,PLUGINS
plugins-list,plugins,READING_LISTING
pml-compute-subpopulation,pml,STATISTIC_ANALYTICS
pml-model-prediction-open,pml,STATISTIC_ANALYTICS
pnotifications-ack,pnotifications,DROP_DELETE
pnotifications-count,pnotifications,DROP_DELETE
pnotifications-get,pnotifications,DROP_DELETE
popular-dataset-manual-compute,popular,DATASET
popular-dataset-manual-compute,popular,OTHER
prediction-train,prediction,MLOPS
prepare-explore-open,prepare,PREPARE
prepare-generate-steps-close,prepare,GENAI_LLM
prepare-generate-steps-open,prepare,GENAI_LLM
prepare-generate-steps-request-aborted,prepare,GENAI_LLM
prepare-generate-steps-request-failed,prepare,GENAI_LLM
prepare-generate-steps-request-start,prepare,GENAI_LLM
prepare-generate-steps-request-successful,prepare,GENAI_LLM
prepare-parsedate-edit-smartdate,prepare,PREPARE
prepare-script-open,prepare,PREPARE
prepare-sql-table-for-write,prepare,CODING
prepare-step-add,prepare,PREPARE
prepare-step-disabled,prepare,PREPARE
prepare-step-enabled,prepare,PREPARE
prepare-step-remove,prepare,PREPARE
prepare-table-refreshed,prepare,PREPARE
prepare-text-to-prepare-open,prepare,PREPARE
prepare-text-to-prepare-request-completion,prepare,PREPARE
prepare-text-to-prepare-request-failed,prepare,PREPARE
prepare-text-to-prepare-request-successful,prepare,PREPARE
prepare-text-to-prepare-start-continue-conversation,prepare,PREPARE
prepare-use-cell-sugg,prepare,PREPARE
prepare-use-col-sugg,prepare,PREPARE
prepare-use-content-sugg,prepare,PREPARE
project-add-exposed-object,project,PROJECTS
project-apikey-get-privileges-for-webapp,project,DROP_DELETE
project-authorization-failure,project,PROJECTS
project-create-from-macro,project,PROJECTS
project-create,project,PROJECTS
project-delete,project,PROJECTS
project-deployer-deploy-bundle-in-existing-deployment,project,PROJECTS
project-deployer-deploy-bundle-in-new-deployment,project,PROJECTS
project-deployer-deployment-create,project,PROJECTS
project-deployer-deployment-delete,project,PROJECTS
project-deployer-deployment-deploy,project,PROJECTS
project-deployer-deployment-details-toggle,project,PROJECTS
project-deployer-deployment-save,project,PROJECTS
project-deployer-deployment-update,project,PROJECTS
project-deployer-infra-save,project,PROJECTS
project-deployer-infra-setup,project,PROJECTS
project-deployer-packages-delete,project,PROJECTS
project-deployer-publish-to-deployer,project,PROJECTS
project-download,project,PROJECTS
project-duplicate,project,PROJECTS
project-export-download,project,PROJECTS
project-export,project,PROJECTS
project-flow-get-graph,project,DROP_DELETE
project-flow-rendered,project,PROJECTS
project-folder-edit-create,project,PROJECTS
project-folder-edit-delete,project,PROJECTS
project-folder-edit-download,project,PROJECTS
project-folder-edit-get,project,DROP_DELETE
project-folder-edit-list,project,READING_LISTING
project-folder-edit-preview-image,project,PROJECTS
project-folder-edit-save,project,PROJECTS
project-folders-get,project,DROP_DELETE
project-folders-hierarchy,project,PROJECTS
project-folders-project-move,project,PROJECTS
project-get-additional-users,project,DROP_DELETE
project-get-dashboard-authorizations,project,DROP_DELETE
project-get-diff,project,DROP_DELETE
project-get-exposed-objects,project,DROP_DELETE
project-get-ext-libs,project,DROP_DELETE
project-get-meta,project,DROP_DELETE
project-get-object-exposition-authorization,project,DROP_DELETE
project-get-permissions,project,DROP_DELETE
project-get-project-access-info,project,DROP_DELETE
project-get-settings,project,DROP_DELETE
project-get-summary,project,DROP_DELETE
project-get-tags,project,DROP_DELETE
project-get-timeline-description,project,DROP_DELETE
project-get-variables,project,DROP_DELETE
project-git-full-status,project,PROJECTS
project-git-get-dirty,project,DROP_DELETE
project-git-list-branches-by-type,project,READING_LISTING
project-git-list-branches,project,READING_LISTING
project-git-push,project,PROJECTS
project-git-remove-remote-repository,project,PROJECTS
project-git-set-dirty-multiple,project,PROJECTS
project-git-set-remote-repository,project,PROJECTS
project-governance-status-get,project,DROP_DELETE
project-import-prepare,project,PROJECTS
project-import,project,PROJECTS
project-integration-add,project,PROJECTS
project-libraries-read,project,READING_LISTING
project-libraries-write,project,PROJECTS
project-libs-git-ref-push-all,project,PROJECTS
project-libs-git-refs-pull-all,project,PROJECTS
project-libs-git-refs-pull-one,project,PROJECTS
project-libs-git-refs-rm,project,PROJECTS
project-libs-git-refs-save,project,PROJECTS
project-list-display-mode,project,READING_LISTING
project-list-folder-effective-reader,project,READING_LISTING
project-list-folder-permissions,project,READING_LISTING
project-list-move-dragndrop,project,READING_LISTING
project-pull-git-ref,project,PROJECTS
project-read-apikey,project,READING_LISTING
project-read-apikeys,project,READING_LISTING
project-read-dashboard-authorizations,project,READING_LISTING
project-read-meta,project,READING_LISTING
project-read-status,project,READING_LISTING
project-read-timeline-meta,project,READING_LISTING
project-resolved-variables-get,project,DROP_DELETE
project-revert-commit,project,PROJECTS
project-revert,project,PROJECTS
project-rm-git-ref,project,PROJECTS
project-save-dashboard-authorizations,project,PROJECTS
project-save-meta,project,PROJECTS
project-save-permissions-non-admin,project,PROJECTS
project-save-permissions,project,PROJECTS
project-save-settings,project,PROJECTS
project-save-variables,project,PROJECTS
project-set-git-ref,project,PROJECTS
project-standards-bundle-check-update,project,PROJECTS
project-standards-bundle-checks-get,project,DROP_DELETE
project-standards-bundle-checks-import,project,PROJECTS
project-standards-bundle-scopes-get,project,DROP_DELETE
project-standards-bundle-scopes-set,project,PROJECTS
project-standards-general-parameters-get,project,DROP_DELETE
project-standards-last-report,project,PROJECTS
project-standards-list-bundle-check-specs,project,READING_LISTING
project-standards-list-tags,project,READING_LISTING
project-standards-run,project,PROJECTS
project-standards-scope-for-project,project,PROJECTS
project-variables-get,project,DROP_DELETE
project-variables-save,project,PROJECTS
project-variables-set,project,PROJECTS
projectdeployer-deployment-list,projectdeployer,READING_LISTING
projectdeployer-deployments-list-tags,projectdeployer,READING_LISTING
projectdeployer-deployments-list,projectdeployer,READING_LISTING
projectdeployer-get-status,projectdeployer,DROP_DELETE
projectdeployer-infra-get-light-status,projectdeployer,DROP_DELETE
projectdeployer-infra-get-settings,projectdeployer,DROP_DELETE
projectdeployer-infra-list-connections,projectdeployer,READING_LISTING
projectdeployer-infra-list-container-exec-names,projectdeployer,READING_LISTING
projectdeployer-infra-list-other-automation-node-urls,projectdeployer,READING_LISTING
projectdeployer-infra-list-user-logins,projectdeployer,READING_LISTING
projectdeployer-infra-status,projectdeployer,DEPLOYER
projectdeployer-infras-list,projectdeployer,READING_LISTING
projectdeployer-services-list,projectdeployer,READING_LISTING
projects-git-commit,projects,GIT
projects-git-create-branch-and-duplicate,projects,GIT
projects-git-create-branch,projects,GIT
projects-git-delete-branches,projects,GIT
projects-git-fetch,projects,GIT
projects-git-pull,projects,GIT
projects-git-push,projects,GIT
projects-git-remove-remote,projects,GIT
projects-git-reset,projects,GIT
projects-git-set-remote,projects,GIT
projects-git-switch-branch,projects,GIT
projects-list,projects,READING_LISTING
prompt-recipe-edit-in-studio,prompt,GENAI_LLM
prompt-studio-comparison-execute-done,prompt,GENAI_LLM
prompt-studio-get-metadata,prompt,DROP_DELETE
prompt-studio-get-prompt-dataset-preview,prompt,DROP_DELETE
prompt-studio-get-responses,prompt,DROP_DELETE
prompt-studio-get,prompt,DROP_DELETE
prompt-studio-llms-load,prompt,GENAI_LLM
prompt-studio-load,prompt,GENAI_LLM
prompt-studio-new-prompt-modal-new-chat,prompt,MLOPS
prompt-studio-new-prompt-modal-new-from-template,prompt,MLOPS
prompt-studio-new-prompt-modal-new-prompt-template,prompt,MLOPS
prompt-studio-new-prompt-modal-new-raw-prompt,prompt,MLOPS
prompt-studio-new-prompt-modal-open,prompt,MLOPS
prompt-studio-prompt-delete,prompt,GENAI_LLM
prompt-studio-prompt-duplicate,prompt,GENAI_LLM
prompt-studio-prompt-execute-done,prompt,GENAI_LLM
prompt-studio-prompt-history-open,prompt,GENAI_LLM
prompt-studio-prompt-history-revert-to-past-run,prompt,GENAI_LLM
prompt-studio-prompt-mode-switch,prompt,GENAI_LLM
prompt-studio-prompt-save-as-recipe-start,prompt,GENAI_LLM
prompt-studio-prompt-settings-edit,prompt,GENAI_LLM
prompt-studio-start-execute,prompt,GENAI_LLM
promptstudios-list,promptstudios,READING_LISTING
proxyuser-denied,proxyuser,DROP_DELETE
publicapi-general-settings-edit,publicapi,APIS
publicapi-general-settings-edit,publicapi,OTHER
publicapi-general-settings-get,publicapi,DROP_DELETE
publicapi-get-node-id,publicapi,DROP_DELETE
publicapi-get-node-type,publicapi,DROP_DELETE
publicapi-invalidate-config-common-files-cache,publicapi,APIS
publicapi-invalidate-config-common-files-cache,publicapi,OTHER
publicapi-key-create,publicapi,APIS
publicapi-key-create,publicapi,OTHER
publicapi-key-delete,publicapi,APIS
publicapi-key-delete,publicapi,OTHER
publicapi-key-edit,publicapi,APIS
publicapi-key-edit,publicapi,OTHER
publicapi-key-get,publicapi,DROP_DELETE
publicapi-keys-list,publicapi,READING_LISTING
publicapi-nodes-directory-edit,publicapi,APIS
publicapi-nodes-directory-edit,publicapi,OTHER
publicapi-variables-edit,publicapi,APIS
publicapi-variables-edit,publicapi,OTHER
publicapi-variables-get,publicapi,DROP_DELETE
publish-to-deployer,publish,DEPLOYER
push-base-images,push,DROP_DELETE
recipe-check-notebook-edition,recipe,CODING
recipe-copy-customcode_cache-table,recipe,VISUAL_RECIPES
recipe-copy-customcode_forward_geocoding,recipe,VISUAL_RECIPES
recipe-copy-distinct,recipe,VISUAL_RECIPES
recipe-copy-evaluation,recipe,VISUAL_RECIPES
recipe-copy-grouping,recipe,VISUAL_RECIPES
recipe-copy-join,recipe,VISUAL_RECIPES
recipe-copy-nlp_llm_user_provided_classification,recipe,GENAI_LLM
recipe-copy-prepare,recipe,VISUAL_RECIPES
recipe-copy-prompt,recipe,GENAI_LLM
recipe-copy-python,recipe,CODING
recipe-copy-sampling,recipe,VISUAL_RECIPES
recipe-copy-shaker,recipe,VISUAL_RECIPES
recipe-copy-sort,recipe,VISUAL_RECIPES
recipe-copy-spark_sql_query,recipe,CODING
recipe-copy-split,recipe,VISUAL_RECIPES
recipe-copy-sql_query,recipe,CODING
recipe-copy-sql_script,recipe,CODING
recipe-copy-sync,recipe,VISUAL_RECIPES
recipe-copy-vstack,recipe,VISUAL_RECIPES
recipe-copy-window,recipe,VISUAL_RECIPES
recipe-create-distinct,recipe,VISUAL_RECIPES
recipe-create-download,recipe,VISUAL_RECIPES
recipe-create-eda_pca,recipe,STATISTIC_ANALYTICS
recipe-create-eda_stats,recipe,STATISTIC_ANALYTICS
recipe-create-eda_univariate,recipe,STATISTIC_ANALYTICS
recipe-create-embed_documents,recipe,GENAI_LLM
recipe-create-fuzzyjoin,recipe,VISUAL_RECIPES
recipe-create-generate_features,recipe,GENAI_LLM
recipe-create-geojoin,recipe,VISUAL_RECIPES
recipe-create-grouping,recipe,VISUAL_RECIPES
recipe-create-join,recipe,VISUAL_RECIPES
recipe-create-list_folder_contents,recipe,READING_LISTING
recipe-create-managed-folder,recipe,VISUAL_RECIPES
recipe-create-merge_folder,recipe,VISUAL_RECIPES
recipe-create-model-evaluation-store,recipe,MLOPS
recipe-create-nlp_llm_model_provided_classification,recipe,GENAI_LLM
recipe-create-nlp_llm_rag_embedding,recipe,GENAI_LLM
recipe-create-nlp_llm_summarization,recipe,GENAI_LLM
recipe-create-nlp_llm_user_provided_classification,recipe,GENAI_LLM
recipe-create-pivot,recipe,VISUAL_RECIPES
recipe-create-prediction_scoring,recipe,VISUAL_RECIPES
recipe-create-prepare,recipe,VISUAL_RECIPES
recipe-create-prompt,recipe,GENAI_LLM
recipe-create-sampling,recipe,VISUAL_RECIPES
recipe-create-shaker,recipe,VISUAL_RECIPES
recipe-create-sort,recipe,VISUAL_RECIPES
recipe-create-sync,recipe,VISUAL_RECIPES
recipe-create-topn,recipe,VISUAL_RECIPES
recipe-create-undefined,recipe,VISUAL_RECIPES
recipe-create-update,recipe,VISUAL_RECIPES
recipe-create-vstack,recipe,VISUAL_RECIPES
recipe-create-window,recipe,VISUAL_RECIPES
recipe-create,recipe,VISUAL_RECIPES
recipe-delete,recipe,VISUAL_RECIPES
recipe-edit-in-notebook,recipe,CODING
recipe-get-variables,recipe,DROP_DELETE
recipe-get,recipe,DROP_DELETE
recipe-open,recipe,VISUAL_RECIPES
recipe-rename,recipe,VISUAL_RECIPES
recipe-run-finished,recipe,VISUAL_RECIPES
recipe-run-start-blocked,recipe,VISUAL_RECIPES
recipe-run-start-failed,recipe,VISUAL_RECIPES
recipe-run-start-forced,recipe,VISUAL_RECIPES
recipe-run-start-no-validation,recipe,VISUAL_RECIPES
recipe-run-start-validated,recipe,VISUAL_RECIPES
recipe-run-start,recipe,VISUAL_RECIPES
recipe-running-abort,recipe,VISUAL_RECIPES
recipe-save,recipe,VISUAL_RECIPES
recipe-update-sm-usabilities,recipe,VISUAL_RECIPES
recipes-list,recipes,READING_LISTING
refresh-catalogs,refresh,SCENARIOS
refresh-project-integrations-list,refresh,READING_LISTING
refresh-scenarios-gantt,refresh,SCENARIOS
refresh-scenarios-list,refresh,READING_LISTING
refresh-scenarios-outcomes,refresh,SCENARIOS
refresh-scenarios-with-reporters-list,refresh,READING_LISTING
refresh-schemas,refresh,SCENARIOS
regular-join-params,regular,VISUAL_RECIPES
remove-objects-from-workspace,remove,DROP_DELETE
render-flow-documentation,render,MLOPS
render-model-documentation,render,MLOPS
report-build,report,WIKI_ARTICAL_DISCUSSIONS
report-create,report,WIKI_ARTICAL_DISCUSSIONS
report-download,report,WIKI_ARTICAL_DISCUSSIONS
report-save,report,WIKI_ARTICAL_DISCUSSIONS
reports-list,reports,READING_LISTING
request-upgrade-profile-open-modal,request,DROP_DELETE
request-upgrade-profile-show,request,DROP_DELETE
requests-center-request-approve,requests,DROP_DELETE
requests-center-request-create,requests,DROP_DELETE
requests-center-request-get-latest,requests,DROP_DELETE
requests-center-request-get,requests,DROP_DELETE
requests-center-request-manage,requests,DROP_DELETE
requests-center-request-show,requests,DROP_DELETE
requests-center-request-type-disabled,requests,DROP_DELETE
requests-center-request-type-enabled,requests,DROP_DELETE
requests-center-request-type-inherit,requests,DROP_DELETE
requests-center-requests-list,requests,DROP_DELETE
rightpanelrecipe_actions_insertrecipe,rightpanelrecipe_actions_insertrecipe,FLOW
rightpanelrecipe_actions_snipandreconnect,rightpanelrecipe_actions_snipandreconnect,FLOW
runnable-abort,runnable,SCENARIOS
runnable-run,runnable,SCENARIOS
running-list-all,running,DROP_DELETE
running-list-personal,running,DROP_DELETE
runs-search,runs,SCENARIOS
runs-to-scenario-run,runs,SCENARIOS
samples,samples,READING_LISTING
save-back-to-recipe,save,DROP_DELETE
save-dataset-data-quality-rules,save,DROP_DELETE
save-snippet,save,DROP_DELETE
save-worksheet,save,DROP_DELETE
saved-model-create-external,saved,MLOPS
saved-model-open,saved,MLOPS
savedmodel-contextual-menu-train,savedmodel,MLOPS
savedmodel-create,savedmodel,MLOPS
savedmodel-deploy-proxy,savedmodel,MLOPS
savedmodel-get-model-details,savedmodel,DROP_DELETE
savedmodel-get-status,savedmodel,DROP_DELETE
savedmodel-get-version-details,savedmodel,DROP_DELETE
savedmodel-get-versions,savedmodel,DROP_DELETE
savedmodel-get,savedmodel,DROP_DELETE
savedmodel-increment-last-train,savedmodel,MLOPS
savedmodel-list-deployments,savedmodel,READING_LISTING
savedmodel-pml-predicted-table-open,savedmodel,MLOPS
savedmodel-read-meta,savedmodel,READING_LISTING
savedmodel-set-active,savedmodel,MLOPS
savedmodels-governance-status-get,savedmodels,DROP_DELETE
savedmodels-list,savedmodels,READING_LISTING
scenario-abort,scenario,SCENARIOS
scenario-create,scenario,SCENARIOS
scenario-creation-modal,scenario,SCENARIOS
scenario-delete,scenario,SCENARIOS
scenario-duplicate,scenario,SCENARIOS
scenario-fire-trigger,scenario,SCENARIOS
scenario-get-history,scenario,DROP_DELETE
scenario-get-test-runs,scenario,DROP_DELETE
scenario-get,scenario,DROP_DELETE
scenario-manual-run-from-dashboard,scenario,SCENARIOS
scenario-manual-run-from-list,scenario,READING_LISTING
scenario-manual-run-with-params,scenario,SCENARIOS
scenario-manual-run,scenario,SCENARIOS
scenario-refresh-runs,scenario,SCENARIOS
scenario-reporter-add,scenario,SCENARIOS
scenario-reporter-remove,scenario,SCENARIOS
scenario-run-step,scenario,SCENARIOS
scenario-run,scenario,SCENARIOS
scenario-save-active,scenario,SCENARIOS
scenario-save,scenario,SCENARIOS
scenario-send-message,scenario,SCENARIOS
scenario-settings-marked-as-test-toggle,scenario,SCENARIOS
scenario-step-add,scenario,SCENARIOS
scenario-step-disable,scenario,SCENARIOS
scenario-step-enable,scenario,SCENARIOS
scenario-step-remove,scenario,SCENARIOS
scenario-steps-paste,scenario,SCENARIOS
scenario-trigger-add,scenario,SCENARIOS
scenario-trigger-remove,scenario,SCENARIOS
scenario-variables-get,scenario,DROP_DELETE
scenario-variables-set,scenario,SCENARIOS
scenarios-get-history,scenarios,DROP_DELETE
scenarios-list,scenarios,READING_LISTING
schedule-scenario-create,schedule,SCENARIOS
schedule-scenario-modal,schedule,SCENARIOS
search-notebooks-list,search,READING_LISTING
security-admin-group-create,security,ADMINISTRATION
security-admin-group-delete,security,ADMINISTRATION
security-admin-group-edit,security,ADMINISTRATION
security-admin-group-get,security,DROP_DELETE
security-admin-group-prepare-delete,security,ADMINISTRATION
security-admin-groups-list,security,READING_LISTING
security-admin-user-activity,security,ADMINISTRATION
security-admin-user-create,security,ADMINISTRATION
security-admin-user-delete,security,ADMINISTRATION
security-admin-user-edit,security,ADMINISTRATION
security-admin-user-get-fetchable-source-types,security,DROP_DELETE
security-admin-user-get-syncable-source-types,security,DROP_DELETE
security-admin-user-get,security,DROP_DELETE
security-admin-user-on-demand-sync-from-source,security,ADMINISTRATION
security-admin-user-patch,security,ADMINISTRATION
security-admin-user-prepare-edit,security,ADMINISTRATION
security-admin-user-start-trial,security,ADMINISTRATION
security-admin-users-list-activity,security,READING_LISTING
security-admin-users-list,security,READING_LISTING
security-connected-users-list,security,READING_LISTING
security-get-auth-info,security,DROP_DELETE
security-groups-list-and-options,security,READING_LISTING
security-groups-list,security,READING_LISTING
security-list-users-matching-email,security,READING_LISTING
security-own-user-get,security,DROP_DELETE
security-users-list,security,READING_LISTING
set_run_inference_info,set_run_inference_info,MLOPS
set-data-steward,set,DROP_DELETE
set-metadata,set,DROP_DELETE
set-recipes-code-env,set,DROP_DELETE
set-recipes-engines,set,DROP_DELETE
shaker-explore-open,shaker,PREPARE
shaker-parsedate-edit-smartdate,shaker,PREPARE
shaker-script-open,shaker,PREPARE
shaker-step-add,shaker,PREPARE
shaker-step-disabled,shaker,PREPARE
shaker-step-enabled,shaker,PREPARE
shaker-step-remove,shaker,PREPARE
shaker-table-refreshed,shaker,PREPARE
shaker-use-cell-sugg,shaker,PREPARE
shaker-use-col-sugg,shaker,PREPARE
shaker-use-content-sugg,shaker,PREPARE
shell-recipe-validate,shell,DROP_DELETE
smartdate-accept,smartdate,PREPARE
smartdate-guessed,smartdate,PREPARE
smartdate-open,smartdate,PREPARE
smartdate-validate-custom,smartdate,PREPARE
sol-webapp-action,sol,WEBAPPS
sol-webapp-action,webapp,WEBAPPS
sol-webapp-open,sol,WEBAPPS
sol-webapp-open,webapp,WEBAPPS
solution-browsed,solution,MLOPS
solution-modal-opened,solution,MLOPS
sparksql-query-validate,sparksql,CODING
sql-notebook-abort,sql,CODING
sql-notebook-add-cell,sql,CODING
sql-notebook-clear-history,sql,CODING
sql-notebook-copy,sql,CODING
sql-notebook-create-recipe,sql,CODING
sql-notebook-create,sql,CODING
sql-notebook-duplicate-cell,sql,CODING
sql-notebook-execute,sql,CODING
sql-notebook-export-results,sql,CODING
sql-notebook-export,sql,CODING
sql-notebook-load,sql,CODING
sql-notebook-run,sql,CODING
sql-notebook-save,sql,CODING
sql-query-fetch,sql,CODING
sql-query-run,sql,CODING
sql-query-start,sql,CODING
sql-query-started,sql,CODING
sql-query-validate,sql,CODING
sql-query-verify,sql,CODING
sql-script-autocomplete,sql,CODING
sql-script-validate,sql,CODING
star-object,star,DROP_DELETE
start-code-explanation,start,MLOPS
start-dataset-explanation,start,MLOPS
start-flow-zone-explanation,start,MLOPS
start-project-explanation,start,MLOPS
start-recipe-generation,start,MLOPS
start-remote-kernel,start,MLOPS
start-retrain-model,start,MLOPS
statistics-card-compute,statistics,STATISTIC_ANALYTICS
statistics-drag-drop-header-card-column,statistics,STATISTIC_ANALYTICS
statistics-drag-drop-reorder-cards,statistics,STATISTIC_ANALYTICS
statistics-drag-drop-variables,statistics,STATISTIC_ANALYTICS
statistics-interactive-query-run,statistics,STATISTIC_ANALYTICS
statistics-sample-build,statistics,STATISTIC_ANALYTICS
statistics-sample-get,statistics,DROP_DELETE
statistics-worksheet-get,statistics,DROP_DELETE
statistics-worksheet-highlight-toggle,statistics,STATISTIC_ANALYTICS
statistics-worksheet-save,statistics,STATISTIC_ANALYTICS
statistics-worksheet-suggester-session,statistics,STATISTIC_ANALYTICS
statistics-worksheets-get,statistics,DROP_DELETE
statistics-worksheets-list,statistics,READING_LISTING
statistics-worksheets-run,statistics,STATISTIC_ANALYTICS
stop-grid-search,stop,MLOPS
story-datastory-get-members,story,DROP_DELETE
story-datastory-get,story,DROP_DELETE
streaming-endpoint-creation-modal,streaming,CODING
streamingendpoint-list,streamingendpoint,READING_LISTING
studio-open,studio,CODING
table-import-candidates-from-explorer,table,MISC_RECIPES
taggable-items-delete-many,taggable,DROP_DELETE
taggable-object-clear-data,taggable,DROP_DELETE
taggable-object-delete,taggable,DROP_DELETE
tagging-apply,tagging,DROP_DELETE
tags-edit,tags,DROP_DELETE
tags-list,tags,DROP_DELETE
tags-usage,tags,DROP_DELETE
test-copy-subflow,test,FLOW
ticket-folder-get,ticket,DROP_DELETE
toggle-dataset-data-quality-enabled,toggle,DATASET
toggle-dataset-data-quality-enabled,toggle,OTHER
toggle-dataset-data-quality-monitoring-flag,toggle,DATASET
toggle-dataset-data-quality-monitoring-flag,toggle,OTHER
trusted-code-report-get,trusted,DROP_DELETE
tutorial-create,tutorial,PROJECTS
tutorial-project-created,tutorial,PROJECTS
tutorial-project-creating,tutorial,PROJECTS
tutorial-project-creation-failed,tutorial,PROJECTS
tutorial-project-open,tutorial,PROJECTS
undefined,undefined,DROP_DELETE
unified-monitoring-alert-list,unified,READING_LISTING
unified-monitoring-api-endpoint-deployment-get-activity-and-system-metrics,unified,DROP_DELETE
unified-monitoring-api-endpoints-get,unified,DROP_DELETE
unified-monitoring-api-endpoints-list,unified,READING_LISTING
unified-monitoring-api-run-as-user-login,unified,DEPLOYER
unified-monitoring-automation-data-quality-status-get,unified,DROP_DELETE
unified-monitoring-automation-latest-scenario-run-get,unified,DROP_DELETE
unified-monitoring-automation-model-status-get,unified,DROP_DELETE
unified-monitoring-deployed-projects-list,unified,READING_LISTING
unified-monitoring-design-model-status-get,unified,DROP_DELETE
unified-monitoring-external-api-endpoints-get-activity-metrics,unified,DROP_DELETE
unified-monitoring-filter-search-changed,unified,DEPLOYER
unified-monitoring-get-logs,unified,DROP_DELETE
unified-monitoring-managed-api-endpoint-get-activity-metrics,unified,DROP_DELETE
unified-monitoring-project-modal-opening,unified,MLOPS
unified-monitoring-projects-page-opening,unified,DEPLOYER
unified-monitoring-settings-remote-design-nodes-urls,unified,DEPLOYER
unified-monitoring-settings,unified,DEPLOYER
unified-monitoring-sort-table,unified,DEPLOYER
unknown-api-key,unknown,APIS
unknown-api-key,unknown,OTHER
upload-files-dataset-create,upload,DATASET
upload-files-dataset-create,upload,OTHER
user-accessible-code-envs-check-agents-code-env,user,USER_MAINTENANCE
user-accessible-code-envs-get-packages,user,DROP_DELETE
user-accessible-code-envs-settings,user,USER_MAINTENANCE
user-code-envs-list,user,READING_LISTING
user-create,user,USER_MAINTENANCE
user-delete,user,USER_MAINTENANCE
user-disable,user,USER_MAINTENANCE
user-edit,user,USER_MAINTENANCE
user-enable,user,USER_MAINTENANCE
user-folder-edit-get,user,DROP_DELETE
user-folder-edit-list,user,READING_LISTING
user-personal-apikey-create,user,USER_MAINTENANCE
user-personal-apikeys-read,user,READING_LISTING
user-profile-action-denied,user,USER_MAINTENANCE
user-profile-create-api-key,user,USER_MAINTENANCE
user-profile-delete-api-key,user,USER_MAINTENANCE
user-profile-delete-credentials,user,USER_MAINTENANCE
user-profile-delete-export,user,USER_MAINTENANCE
user-profile-dismiss-whats-new-popover,user,USER_MAINTENANCE
user-profile-edit-credentials,user,USER_MAINTENANCE
user-profile-get-achievements,user,DROP_DELETE
user-profile-get-questionnaire,user,DROP_DELETE
user-profile-get,user,DROP_DELETE
user-profile-list-connection-credentials,user,READING_LISTING
user-profile-load,user,USER_MAINTENANCE
user-profile-save-settings,user,USER_MAINTENANCE
user-profile-save-user,user,USER_MAINTENANCE
user-profile-set-home-row,user,USER_MAINTENANCE
user-profile-set-plugin-credential,user,USER_MAINTENANCE
user-profile-set-settings,user,USER_MAINTENANCE
user-profile-update-ats-settings,user,USER_MAINTENANCE
user-profile-update-nps-settings,user,USER_MAINTENANCE
user-profile-update-page-specific-tour-settings,user,USER_MAINTENANCE
user-profile-update-questionnaire,user,USER_MAINTENANCE
user-python-code-envs-list-compatibility-with-mltask,user,READING_LISTING
user-python-code-envs-list-with-visual-ml-packages,user,READING_LISTING
visualedit-display-table,visualedit,DROP_DELETE
visualedit-edit-cell,visualedit,DROP_DELETE
wait-write-session,wait,DROP_DELETE
watch-object,watch,DROP_DELETE
webapp-backend-restart,webapp,WEBAPPS
webapp-backend-stop,webapp,WEBAPPS
webapp-backend,webapp,WEBAPPS
webapp-copy,webapp,WEBAPPS
webapp-create,webapp,WEBAPPS
webapp-get-diagnostic,webapp,DROP_DELETE
webapp-get-log,webapp,DROP_DELETE
webapp-get,webapp,DROP_DELETE
webapp-protected-view,webapp,WEBAPPS
webapp-publish,webapp,WEBAPPS
webapp-save,webapp,WEBAPPS
webapp-start,webapp,WEBAPPS
webapp-stop,webapp,WEBAPPS
webapp-trust,webapp,WEBAPPS
webapp-view,webapp,WEBAPPS
webapps-get,webapps,DROP_DELETE
webapps-list-heads,webapps,READING_LISTING
webapps-list,webapps,READING_LISTING
wiki-article-save,wiki,WIKI_ARTICAL_DISCUSSIONS
wiki-export,wiki,WIKI_ARTICAL_DISCUSSIONS
wiki-get,wiki,DROP_DELETE
wiki-set-home,wiki,WIKI_ARTICAL_DISCUSSIONS
wiki-upload,wiki,WIKI_ARTICAL_DISCUSSIONS
wiki-visit,wiki,WIKI_ARTICAL_DISCUSSIONS
wikis-list-authorized-extensions,wikis,READING_LISTING
wikis-list,wikis,READING_LISTING
worksheets_export-card-as-recipe,worksheets_export,MISC_RECIPES
workspace-authorization-failure,workspace,WORKSPACES
workspace-dataset-get,workspace,DROP_DELETE
workspace-dataset-read-data,workspace,READING_LISTING
workspace-get-object,workspace,DROP_DELETE
workspace-get-settings,workspace,DROP_DELETE
workspace-get,workspace,DROP_DELETE
workspace-list-heads,workspace,READING_LISTING
workspace-list,workspace,READING_LISTING
workspace-object-get-thumbnail,workspace,DROP_DELETE
workspaces-add-object-cancel,workspaces,WORKSPACES
workspaces-add-object-open,workspaces,WORKSPACES
workspaces-add-object-success,workspaces,WORKSPACES
workspaces-create-workspace-cancel,workspaces,WORKSPACES
workspaces-create-workspace-open,workspaces,WORKSPACES
workspaces-create-workspace-success,workspaces,WORKSPACES
workspaces-datastory-open,workspaces,WORKSPACES
workspaces-delete-workspace-open,workspaces,WORKSPACES
workspaces-delete-workspace-success,workspaces,WORKSPACES
workspaces-edit-object-cancel,workspaces,WORKSPACES
workspaces-edit-object-open,workspaces,WORKSPACES
workspaces-edit-workspace-cancel,workspaces,WORKSPACES
workspaces-edit-workspace-open,workspaces,WORKSPACES
workspaces-edit-workspace-success,workspaces,WORKSPACES
workspaces-open-object,workspaces,WORKSPACES
workspaces-open-workspace,workspaces,WORKSPACES
workspaces-remove-object-cancel,workspaces,WORKSPACES
workspaces-remove-object-open,workspaces,WORKSPACES
workspaces-remove-object-success,workspaces,WORKSPACES
workspaces-star-object,workspaces,WORKSPACES
zones-read-meta,zones,READING_LISTING
"""